CREATE TABLE rental
	( 
	 rental_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)  NOT NULL,
	 rental_date DATETIME NOT NULL,
	 inventory_id BIGINT NOT NULL,
	 customer_id BIGINT NOT NULL,
	 return_date DATETIME DEFAULT NULL,
	 staff_id BIGINT NOT NULL,
  	 last_update DATETIME NOT NULL,
	 PRIMARY KEY(rental_id)
	 );	 
	 
CREATE TABLE customer
	( 
	 customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)  NOT NULL,
	 store_id BIGINT NOT NULL,
	 first_name VARCHAR(45) NOT NULL,
	 last_name VARCHAR(45) NOT NULL,
	 email VARCHAR(50) DEFAULT NULL,     
	 address_id BIGINT NOT NULL,
	 active BOOLEAN DEFAULT TRUE NOT NULL,
	 create_date DATETIME NOT NULL,
  	 last_update DATETIME,
	 PRIMARY KEY(customer_id)
	 );	

CREATE TABLE city
	( 
	 city_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)  NOT NULL,
	 city VARCHAR(50) NOT NULL,
	 country_id BIGINT NOT NULL,
  	 last_update DATETIME,
	 PRIMARY KEY(city_id)
	 );	 
	 
CREATE TABLE address
	( 
	 address_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)  NOT NULL,
	 address VARCHAR(50) NOT NULL,
	 address2 VARCHAR(50) DEFAULT NULL,
	 district VARCHAR(20) NOT NULL,	 
	 city_id BIGINT NOT NULL,
	 postal_code VARCHAR(10) DEFAULT NULL,
	 phone VARCHAR(20) NOT NULL,
  	 last_update DATETIME,
	 PRIMARY KEY(address_id)
	 );